name: Sync Image to Aliyun ACR

on:
  workflow_dispatch: # 支持手动点击运行
    inputs:
      source_image:
        description: '源镜像 (例如 nextcloud:latest)'
        required: true
        default: 'nextcloud:latest'
      target_tag:
        description: '推送到 ACR 的镜像 Tag (例如 nextcloud-latest)'
        required: true
        default: 'nextcloud-latest'

jobs:
  sync-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Aliyun ACR
        uses: docker/login-action@v3
        with:
          registry: crpi-mrrxzois5w52x7yt.cn-chengdu.personal.cr.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Pull and Push Image
        run: |
          # 1. 拉取海外镜像
          docker pull ${{ github.event.inputs.source_image }}
          
          # 2. 重新打 Tag 为您的专用 ACR 仓库地址
          docker tag ${{ github.event.inputs.source_image }} crpi-mrrxzois5w52x7yt.cn-chengdu.personal.cr.aliyuncs.com/xcz_2026/yczh83116:${{ github.event.inputs.target_tag }}
          
          # 3. 推送到阿里云 ACR
          docker push crpi-mrrxzois5w52x7yt.cn-chengdu.personal.cr.aliyuncs.com/xcz_2026/yczh83116:${{ github.event.inputs.target_tag }}
